name: flutter_starter_boilerplate
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  shared_preferences: ^2.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fpdart: ^0.6.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  crypto: ^3.0.3
  go_router: ^9.0.3
  infinite_scroll_pagination: ^3.2.0
  flutter_screenutil: ^5.8.4
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.6
  mockito: ^5.4.2
  bloc_test: ^9.1.3

flutter:
  uses-material-design: true
  generate: true
